#!/usr/bin/env bash
# tests/test_nasim_claude_prompted.sh
# Generated by nasim+claude over ollama (prompt passed to nasim code --one-shot "...")
# "just pass the prompt and nasim does the coding for you on a file"

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
NASIM_INTERNAL=1 source bin/nasim
export DEFAULT_MODEL="deepseek-r1:14b"

out=$(NASIM_DRY_RUN=1 launch_claude "http://127.0.0.1:11435" "$DEFAULT_MODEL" 2>&1)

vars="ANTHROPIC_API_URL ANTHROPIC_BASE_URL ANTHROPIC_AUTH_TOKEN ANTHROPIC_API_KEY ANTHROPIC_DEFAULT_MAX_OUTPUT_TOKENS ANTHROPIC_DEFAULT_HAIKU_MODEL CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY CLAUDE_CODE_AUTO_COMPACT_WINDOW CLAUDE_CLI_BIN CLAUDE_WORKSPACE"
for v in $vars; do
  echo "$out" | grep -q "$v" || { echo "FAIL missing $v"; exit 1; }
done
echo "PASS: all vars present (prompt-driven test)"
