#!/usr/bin/env bash
# lib/nasim/context.sh — Project context detection + injection (Option A)
#
# context_detect():
#   Auto-detect project type, tech stack, key files from git repo.
#   Generates .nasim/context.md with structured context.
#
# context_inject(agent, url, model, ...):
#   Prepend context to agent launch. For claude, uses --prompt; for aider,
#   sets AIDER_READ environment; for terminal, exports NASIM_CONTEXT.
#
# context_refresh():
#   Re-scan project and regenerate context.md.

NASIM_CONTEXT_DIR=".nasim"
NASIM_CONTEXT_FILE="$NASIM_CONTEXT_DIR/context.md"
NASIM_GLOBAL_CONTEXT_DIR="${HOME}/.local/share/nasim/contexts"

# _context_ensure_dir():
#   Ensure .nasim directory exists in current project.
_context_ensure_dir() {
    mkdir -p "$NASIM_CONTEXT_DIR"
}

# context_detect():
#   Analyze current directory and generate context.md.
#   Detects: language, framework, build system, test setup, key files.
context_detect() {
    local dir="${1:-.}"
    cd "$dir" || return 1

    if [[ ! -d ".git" ]]; then
        log "not a git repository — context detection works best in git projects"
    fi

    _context_ensure_dir

    local lang="unknown"
    local framework=""
    local build=""
    local test=""
    local entry=""

    # Language detection
    if [[ -f "Cargo.toml" ]]; then
        lang="rust"; build="cargo"; test="cargo test"; entry=$(grep -m1 'name' Cargo.toml 2>/dev/null | cut -d\" -f2)
    elif [[ -f "package.json" ]]; then
        lang="javascript/typescript"; build="npm/yarn/pnpm"; test=$(jq -r '.scripts.test // "npm test"' package.json 2>/dev/null)
        framework=$(jq -r '(.dependencies // {}) | keys[]' package.json 2>/dev/null | grep -E 'react|vue|next|express|fastify' | head -1 || true)
    elif [[ -f "pyproject.toml" || -f "setup.py" || -f "requirements.txt" ]]; then
        lang="python"; build="pip/poetry/uv"
        if [[ -f "pyproject.toml" ]]; then
            framework=$(grep -E '^\[tool\.(poetry|uv|hatch)' pyproject.toml | head -1 | sed 's/.*tool\.//' | tr -d '[]')
        fi
        test="pytest"
    elif [[ -f "go.mod" ]]; then
        lang="go"; build="go"; test="go test ./..."; entry=$(grep -m1 'module' go.mod | awk '{print $2}')
    elif [[ -f "Gemfile" ]]; then
        lang="ruby"; build="bundler"; framework="rails"; test="rspec"
    elif [[ -f "composer.json" ]]; then
        lang="php"; build="composer"
    elif [[ -f "pom.xml" || -f "build.gradle" ]]; then
        lang="java"; build="maven/gradle"
    elif [[ -f "CMakeLists.txt" || -f "Makefile" ]]; then
        lang="c/c++"; build="cmake/make"
    elif [[ -f "*.sh" || -d "lib/nasim" ]]; then
        lang="bash/shell"; build="bash"
    fi

    # Key files
    local key_files=""
    key_files=$(find . -maxdepth 2 -type f \( -name "README*" -o -name "*.md" -o -name "Dockerfile" -o -name "docker-compose*" -o -name ".env*" -o -name "*.yaml" -o -name "*.yml" \) ! -path "*/node_modules/*" ! -path "*/.git/*" ! -path "*/target/*" ! -path "*/dist/*" | head -20 | sed 's|^\.\/||')

    # Directory structure (top level)
    local structure=""
    structure=$(find . -maxdepth 1 -type d ! -name ".*" ! -name "node_modules" ! -name "target" ! -name "dist" ! -name "build" | sort | sed 's|^\.\/||' | head -15)

    cat > "$NASIM_CONTEXT_FILE" <<EOF
# Project Context — Auto-generated by nasim
# This file is injected into agent prompts for better code assistance.
# Run \`nasim context --refresh\` to update after major changes.

## Project Overview
- **Language**: $lang
- **Framework**: ${framework:-none detected}
- **Build System**: ${build:-unknown}
- **Test Command**: ${test:-unknown}
- **Entry Point**: ${entry:-unknown}

## Directory Structure (top level)
\`\`\`
$structure
\`\`\`

## Key Files
EOF

    while IFS= read -r f; do
        echo "- $f" >> "$NASIM_CONTEXT_FILE"
    done <<< "$key_files"

    # Add recent git activity if available
    if [[ -d ".git" ]]; then
        echo "" >> "$NASIM_CONTEXT_FILE"
        echo "## Recent Git Activity" >> "$NASIM_CONTEXT_FILE"
        echo "\`\`\`" >> "$NASIM_CONTEXT_FILE"
        git log --oneline -5 2>/dev/null >> "$NASIM_CONTEXT_FILE" || echo "(git log unavailable)" >> "$NASIM_CONTEXT_FILE"
        echo "\`\`\`" >> "$NASIM_CONTEXT_FILE"
        echo "" >> "$NASIM_CONTEXT_FILE"
        echo "## Current Branch" >> "$NASIM_CONTEXT_FILE"
        echo "\`$(git branch --show-current 2>/dev/null || echo unknown)\`" >> "$NASIM_CONTEXT_FILE"
    fi

    # Add dependency summary if detectable
    echo "" >> "$NASIM_CONTEXT_FILE"
    echo "## Dependencies (sample)" >> "$NASIM_CONTEXT_FILE"
    case "$lang" in
        rust)
            grep -E '^\[dependencies\]' -A 20 Cargo.toml 2>/dev/null | head -15 >> "$NASIM_CONTEXT_FILE" || true ;;
        python)
            if [[ -f "pyproject.toml" ]]; then
                grep -E '^\[project\.dependencies\]' -A 20 pyproject.toml 2>/dev/null | head -15 >> "$NASIM_CONTEXT_FILE" || true
            elif [[ -f "requirements.txt" ]]; then
                head -15 requirements.txt >> "$NASIM_CONTEXT_FILE" || true
            fi ;;
        javascript/typescript)
            jq -r '(.dependencies // {}) | to_entries[] | "\(.key): \(.value)"' package.json 2>/dev/null | head -15 >> "$NASIM_CONTEXT_FILE" || true ;;
    esac

    log "context generated: $NASIM_CONTEXT_FILE"
    echo "Tip: Edit this file to add project-specific conventions, API docs, or architecture notes."
}

# context_refresh():
#   Re-detect and regenerate context for current project.
context_refresh() {
    if [[ -f "$NASIM_CONTEXT_FILE" ]]; then
        log "refreshing project context..."
    else
        log "detecting project context..."
    fi
    context_detect "$(pwd)"
}

# context_file():
#   Return path to current context file, or empty if none.
context_file() {
    if [[ -f "$NASIM_CONTEXT_FILE" ]]; then
        echo "$NASIM_CONTEXT_FILE"
    elif [[ -f "${HOME}/.local/share/nasim/global-context.md" ]]; then
        echo "${HOME}/.local/share/nasim/global-context.md"
    else
        echo ""
    fi
}

# context_is_active():
#   True if a context file exists for current project.
context_is_active() {
    [[ -n "$(context_file)" ]]
}

# context_read():
#   Output the contents of the active context file.
context_read() {
    local cf
    cf=$(context_file)
    if [[ -n "$cf" ]]; then
        cat "$cf"
    fi
}

# context_inject_args(agent):
#   Return the appropriate CLI args to inject context into the agent.
#   For claude: --prompt "..." or --system-prompt "..."
#   For aider: not directly supported, so we use env var
#   For terminal: export NASIM_CONTEXT
context_inject_args() {
    local agent="$1"
    local cf
    cf=$(context_file)
    [[ -z "$cf" ]] && return 0

    local ctx
    ctx=$(cat "$cf" 2>/dev/null || true)
    [[ -z "$ctx" ]] && return 0

    case "$agent" in
        claude|code)
            # Claude Code supports --prompt for initial context
            # We use a temp file to avoid shell escaping issues with large context
            local tmpf="/tmp/nasim-context-$$.md"
            echo "$ctx" > "$tmpf"
            echo "--prompt"
            echo "@$tmpf"
            ;;
        aider)
            # Aider doesn't have a direct --prompt, but we can set AIDER_READ
            # or use /read in the chat. For now, export env for aider to see.
            export AIDER_READ="$cf"
            # No CLI args to return
            ;;
        opencode|open)
            # OpenCode may support system prompts via env
            export OPENCODE_SYSTEM_PROMPT="$ctx"
            ;;
        terminal|shell)
            export NASIM_CONTEXT_FILE="$cf"
            echo "# Project context available in \$NASIM_CONTEXT_FILE"
            ;;
    esac
}

# context_global_edit():
#   Edit the global context template that applies to all nasim sessions.
context_global_edit() {
    mkdir -p "$NASIM_GLOBAL_CONTEXT_DIR"
    local gf="$NASIM_GLOBAL_CONTEXT_DIR/global-context.md"
    if [[ ! -f "$gf" ]]; then
        cat > "$gf" <<'EOF'
# Global Nasim Context
# This context is injected into EVERY nasim session.
# Use it for: coding conventions, preferred patterns, personal notes.

## My Preferences
- I prefer explicit error handling over panics/throws
- I write tests for all public functions
- I prefer functional programming patterns where practical

## Tech Stack Preferences
- Rust for systems, Python for ML/DS, TypeScript for web
- PostgreSQL for relational, Redis for cache, SQLite for local
- Docker for deployment, Nix for reproducible dev envs

## Project Notes
# Add notes about specific projects here, or use per-project .nasim/context.md
EOF
    fi
    local editor="${EDITOR:-${VISUAL:-nano}}"
    "$editor" "$gf"
}
