#!/usr/bin/env bash
# lib/nasim/fcc.sh — Isolated free-claude-code proxy sidecar for claude agent + remote ollama
#
# Purpose: When launching claude, if NASIM_FCC_SRC_DIR is available (user cloned
# free-claude-code as instructed), start a *temporary* fcc proxy that:
#   - Points OLLAMA_BASE_URL at the nasim tunnel (raw ollama url)
#   - Sets MODEL=ollama/<tag> (the prefix the proxy and gateway expect)
#   - Serves /v1/models as "anthropic/ollama/..." and "claude-3-freecc-..." gateway ids
#   - Performs full request/response translation, tool streaming, thinking normalization
#     (critical for deepseek-r1 + claude-code agent loops)
#
# This is the main fix for sce1.txt: direct ollama base + bare model name does not
# give claude-code a proper "gateway" model list or exact anthropic message shapes
# it needs for reliable tool dispatch.
#
# The proxy lifetime is tied to nasim (pidfiles + stop/restore). On nasim stop
# the fcc is killed and envs (including ANTHROPIC_BASE_URL pointing at proxy)
# are rolled back so plain claude sees only official anthropic.

NASIM_FCC_STATE_DIR="${NASIM_STATE_DIR:-$HOME/.local/share/nasim}"
NASIM_FCC_PID_FILE="$NASIM_FCC_STATE_DIR/fcc.pid"
NASIM_FCC_ENV_FILE="$NASIM_FCC_STATE_DIR/fcc.env"
NASIM_FCC_PORT_FILE="$NASIM_FCC_STATE_DIR/fcc.port"

_fcc_ensure_dirs() {
    mkdir -p "$NASIM_FCC_STATE_DIR"
}

# _fcc_autodetect():
#   If NASIM_FCC_SRC_DIR not explicitly set, try to find a sibling or common
#   free-claude-code checkout (dev layout: nasim/ next to free-claude-code/).
_fcc_autodetect() {
    if [[ -n "${NASIM_FCC_SRC_DIR:-}" ]]; then
        return 0
    fi
    local candidates=()
    # sibling to the nasim source tree (when running from checkout)
    if [[ -n "${NASIM_LIB_DIR:-}" ]]; then
        candidates+=("$(cd "$NASIM_LIB_DIR/../../../free-claude-code" 2>/dev/null && pwd || true)")
        candidates+=("$(cd "$NASIM_LIB_DIR/../../free-claude-code" 2>/dev/null && pwd || true)")
    fi
    # common locations
    candidates+=(
        "$HOME/prj/salim/nasim/code/free-claude-code"
        "$HOME/prj/nasim/code/free-claude-code"
        "$PWD/../free-claude-code"
        "$PWD/../../free-claude-code"
    )
    for c in "${candidates[@]}"; do
        if [[ -n "$c" && -f "$c/api/app.py" ]]; then
            NASIM_FCC_SRC_DIR="$c"
            return 0
        fi
    done
}

fcc_available() {
    _fcc_autodetect
    [[ -n "${NASIM_FCC_SRC_DIR:-}" && -f "$NASIM_FCC_SRC_DIR/api/app.py" ]] || return 1
    have python3 || return 1
    # uvicorn is the hard runtime dep for the proxy; full stack (fastapi etc) will cause
    # start to fallback cleanly if missing transitive packages. Users with `uv` or the
    # fcc install will get the full gateway experience for claude+ollama tools.
    python3 -c 'import uvicorn' 2>/dev/null || return 1
    return 0
}

_fcc_find_free_port() {
    # Prefer a port near nasim's ollama port; fall back
    local base="${DEFAULT_LOCAL_PORT:-11435}"
    local p=$(( base + 1 ))
    for off in 0 1 2 10 100; do
        local try=$(( base + 1 + off ))
        if ! (echo > /dev/tcp/127.0.0.1/$try) 2>/dev/null; then
            echo "$try"
            return 0
        fi
    done
    # last resort
    python3 -c '
import socket
s=socket.socket(); s.bind(("",0)); print(s.getsockname()[1]); s.close()
' 2>/dev/null || echo 18080
}

fcc_write_temp_config() {
    local ollama_url="$1"
    local model="$2"
    local port="$3"
    _fcc_ensure_dirs

    local bare="${model#ollama/}"
    local fcc_model="ollama/${bare}"

    cat > "$NASIM_FCC_ENV_FILE" <<EOF
# Auto-generated by nasim for this session. Do not edit.
OLLAMA_BASE_URL=${ollama_url}
MODEL=${fcc_model}
ANTHROPIC_AUTH_TOKEN=ollama
PORT=${port}
HOST=127.0.0.1
# Keep admin quiet for CLI use
FCC_OPEN_BROWSER=false
# Reasonable for local
ENABLE_MODEL_THINKING=true
EOF
    echo "$NASIM_FCC_ENV_FILE"
}

fcc_start_proxy() {
    local ollama_url="$1" model="$2"
    _fcc_ensure_dirs

    if [[ -f "$NASIM_FCC_PID_FILE" ]]; then
        local oldpid
        oldpid=$(cat "$NASIM_FCC_PID_FILE" 2>/dev/null || true)
        if [[ -n "$oldpid" ]] && kill -0 "$oldpid" 2>/dev/null; then
            local oldport
            oldport=$(cat "$NASIM_FCC_PORT_FILE" 2>/dev/null || echo 0)
            echo "http://127.0.0.1:${oldport}"
            return 0
        fi
        fcc_stop_proxy
    fi

    if ! fcc_available; then
        log "fcc proxy not available (NASIM_FCC_SRC_DIR or uvicorn missing); using direct ollama"
        echo "$ollama_url"
        return 1
    fi

    local port
    port=$(_fcc_find_free_port)
    local envf
    envf=$(fcc_write_temp_config "$ollama_url" "$model" "$port")

    log "starting isolated fcc proxy (ollama via nasim -> fcc on :$port , model=ollama/${model#ollama/}) ..."

    local fcc_dir="$NASIM_FCC_SRC_DIR"
    # Launch uvicorn bound to the temp env (settings read FCC_ENV_FILE + dotenv)
    # Use --factory because create_app is a factory in some paths
    # Prefer uv (the way fcc itself is developed/installed) so we pull the exact
    # locked deps without polluting user python.
    if have uv; then
        FCC_ENV_FILE="$envf" PYTHONPATH="$fcc_dir" \
        uv --directory "$fcc_dir" --project . run --with uvicorn -- \
            python -m uvicorn \
            --app-dir "$fcc_dir" \
            --factory api.app:create_app \
            --host 127.0.0.1 --port "$port" --log-level error \
            --timeout-graceful-shutdown 3 \
            >/dev/null 2>&1 &
    else
        FCC_ENV_FILE="$envf" PYTHONPATH="$fcc_dir" \
        python3 -m uvicorn \
            --app-dir "$fcc_dir" \
            --factory api.app:create_app \
            --host 127.0.0.1 --port "$port" --log-level error \
            --timeout-graceful-shutdown 3 \
            >/dev/null 2>&1 &
    fi
    local pid=$!
    echo "$pid" > "$NASIM_FCC_PID_FILE"
    echo "$port" > "$NASIM_FCC_PORT_FILE"

    # Wait for health (up to ~8s)
    local proxy_url="http://127.0.0.1:${port}"
    local ok=0
    for i in 1 2 3 4 5 6 7 8; do
        if curl -sf --max-time 1 "${proxy_url}/health" >/dev/null 2>&1; then
            ok=1; break
        fi
        sleep 0.6
    done

    if [[ $ok -eq 1 ]]; then
        log "fcc proxy healthy at $proxy_url"
        echo "$proxy_url"
        return 0
    else
        log "fcc proxy failed to become healthy; killing and falling back to direct"
        kill "$pid" 2>/dev/null || true
        rm -f "$NASIM_FCC_PID_FILE" "$NASIM_FCC_PORT_FILE" "$NASIM_FCC_ENV_FILE"
        echo "$ollama_url"
        return 1
    fi
}

fcc_stop_proxy() {
    _fcc_ensure_dirs
    local killed=0
    if [[ -f "$NASIM_FCC_PID_FILE" ]]; then
        local pid
        pid=$(cat "$NASIM_FCC_PID_FILE" 2>/dev/null || true)
        if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
            log "stopping fcc proxy (pid $pid)"
            kill "$pid" 2>/dev/null || true
            sleep 0.3
            kill -9 "$pid" 2>/dev/null || true
            killed=1
        fi
        rm -f "$NASIM_FCC_PID_FILE"
    fi
    rm -f "$NASIM_FCC_PORT_FILE" "$NASIM_FCC_ENV_FILE" 2>/dev/null || true
    [[ $killed -eq 1 ]] && log "fcc proxy stopped"
}

# Auto cleanup hooks (best effort)
if [[ "${NASIM_TOP_LEVEL:-}" == "1" ]]; then
    # Register with existing EXIT trap chain if possible; daemon/rollback already do traps.
    # We append a kill here too for safety on direct claude launches.
    trap 'fcc_stop_proxy' EXIT INT TERM HUP 2>/dev/null || true
fi

# For orchestration/daemon stop to call us
fcc_cleanup_on_stop() {
    fcc_stop_proxy
}