"""Project context detection + injection.

Detects language/framework/build/test and key files for the current git project and
writes ``.nasim/context.md``, which agents can load for better assistance. Mirrors
``context.sh`` using native Python file inspection.

Functions:
    detect: Analyse a directory and write context.md.
    refresh: Re-detect for the current project.
    context_file: Path to the active context file ("" if none).
    is_active: Whether a context file exists.
    read: Contents of the active context file.
    global_edit: Open the global context template in $EDITOR.
"""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

from nasim import config
from nasim.util import capture, log

CONTEXT_DIR = ".nasim"
CONTEXT_FILE = os.path.join(CONTEXT_DIR, "context.md")


def _detect_language(a_root: Path) -> tuple[str, str, str, str, str]:
    """Detect language/framework/build/test/entry from marker files.

    Args:
        a_root (Path): Project root.

    Returns:
        tuple[str, str, str, str, str]: (lang, framework, build, test, entry).
    """
    lang, framework, build, test, entry = "unknown", "", "", "", ""
    if (a_root / "Cargo.toml").is_file():
        lang, build, test = "rust", "cargo", "cargo test"
    elif (a_root / "package.json").is_file():
        lang, build, test = "javascript/typescript", "npm/yarn/pnpm", "npm test"
        try:
            pkg = json.loads((a_root / "package.json").read_text(encoding="utf-8"))
            test = pkg.get("scripts", {}).get("test", "npm test")
            deps = list(pkg.get("dependencies", {}).keys())
            framework = next((d for d in deps if d in ("react", "vue", "next", "express", "fastify")), "")
        except (OSError, ValueError):
            pass
    elif any((a_root / f).is_file() for f in ("pyproject.toml", "setup.py", "requirements.txt")):
        lang, build, test = "python", "pip/poetry/uv", "pytest"
    elif (a_root / "go.mod").is_file():
        lang, build, test = "go", "go", "go test ./..."
    elif (a_root / "Gemfile").is_file():
        lang, build, framework, test = "ruby", "bundler", "rails", "rspec"
    elif (a_root / "composer.json").is_file():
        lang, build = "php", "composer"
    elif (a_root / "pom.xml").is_file() or (a_root / "build.gradle").is_file():
        lang, build = "java", "maven/gradle"
    elif (a_root / "CMakeLists.txt").is_file() or (a_root / "Makefile").is_file():
        lang, build = "c/c++", "cmake/make"
    elif (a_root / "lib" / "nasim").is_dir() or list(a_root.glob("*.sh")):
        lang, build = "bash/shell", "bash"
    return lang, framework, build, test, entry


def detect(a_dir: str = ".") -> None:
    """Analyse a directory and write ``.nasim/context.md``.

    Args:
        a_dir (str): Directory to analyse (defaults to cwd).
    """
    root = Path(a_dir).resolve()
    os.chdir(root)
    if not (root / ".git").is_dir():
        log("not a git repository — context detection works best in git projects")
    Path(CONTEXT_DIR).mkdir(parents=True, exist_ok=True)

    lang, framework, build, test, entry = _detect_language(root)

    structure = sorted(
        p.name
        for p in root.iterdir()
        if p.is_dir() and not p.name.startswith(".") and p.name not in ("node_modules", "target", "dist", "build")
    )[:15]

    key_files = []
    for p in root.rglob("*"):
        if len(key_files) >= 20:
            break
        rel = p.relative_to(root)
        if len(rel.parts) > 2 or any(seg in (".git", "node_modules", "target", "dist") for seg in rel.parts):
            continue
        name = p.name
        if p.is_file() and (
            name.startswith("README")
            or name.endswith((".md", ".yaml", ".yml"))
            or name in ("Dockerfile",)
            or name.startswith("docker-compose")
            or name.startswith(".env")
        ):
            key_files.append(str(rel))

    lines = [
        "# Project Context — Auto-generated by nasim",
        "# This file is injected into agent prompts for better code assistance.",
        "# Run `nasim context --refresh` to update after major changes.",
        "",
        "## Project Overview",
        f"- **Language**: {lang}",
        f"- **Framework**: {framework or 'none detected'}",
        f"- **Build System**: {build or 'unknown'}",
        f"- **Test Command**: {test or 'unknown'}",
        f"- **Entry Point**: {entry or 'unknown'}",
        "",
        "## Directory Structure (top level)",
        "```",
        *structure,
        "```",
        "",
        "## Key Files",
        *[f"- {f}" for f in key_files],
    ]

    if (root / ".git").is_dir():
        git_log = capture(["git", "log", "--oneline", "-5"]) or "(git log unavailable)"
        branch = capture(["git", "branch", "--show-current"]) or "unknown"
        lines += ["", "## Recent Git Activity", "```", git_log, "```", "", "## Current Branch", f"`{branch}`"]

    Path(CONTEXT_FILE).write_text("\n".join(lines) + "\n", encoding="utf-8")
    log(f"context generated: {CONTEXT_FILE}")
    print("Tip: Edit this file to add project-specific conventions, API docs, or architecture notes.")


def refresh() -> None:
    """Re-detect and regenerate context for the current project."""
    log("refreshing project context..." if Path(CONTEXT_FILE).is_file() else "detecting project context...")
    detect(os.getcwd())


def context_file() -> str:
    """Return the active context file path, or "" if none.

    Returns:
        str: Path to the project or global context file, else empty string.
    """
    result = ""
    if Path(CONTEXT_FILE).is_file():
        result = CONTEXT_FILE
    else:
        global_ctx = config.STATE_DIR / "global-context.md"
        if global_ctx.is_file():
            result = str(global_ctx)
    return result


def is_active() -> bool:
    """Return whether a context file exists.

    Returns:
        bool: True if a project or global context file is present.
    """
    return bool(context_file())


def read() -> str:
    """Return the contents of the active context file ("" if none).

    Returns:
        str: Context text.
    """
    cf = context_file()
    out = ""
    if cf:
        try:
            out = Path(cf).read_text(encoding="utf-8")
        except OSError:
            out = ""
    return out


def global_edit() -> None:
    """Open the global context template in the user's editor."""
    config.GLOBAL_CONTEXT_DIR.mkdir(parents=True, exist_ok=True)
    gf = config.GLOBAL_CONTEXT_DIR / "global-context.md"
    if not gf.is_file():
        gf.write_text(
            "# Global Nasim Context\n"
            "# This context is injected into EVERY nasim session.\n\n"
            "## My Preferences\n"
            "- (add coding conventions, preferred patterns, personal notes)\n",
            encoding="utf-8",
        )
    editor = os.environ.get("EDITOR") or os.environ.get("VISUAL") or "nano"
    subprocess.run([editor, str(gf)])
