"""Isolated free-claude-code (fcc) proxy sidecar for the Claude agent.

When a ``free-claude-code`` checkout is available, launching Claude can route through
a temporary fcc proxy that points at the nasim tunnel, exposes gateway model ids, and
performs full Anthropic<->Ollama request/response translation (richer tool-calling
than the raw Ollama Anthropic-compat surface). The proxy's lifetime is tied to nasim:
it is killed on stop/rollback so plain Claude later sees only official Anthropic.

Functions:
    autodetect: Locate a free-claude-code source dir if not configured.
    available: True if the proxy can be started here.
    start_proxy: Start (or reuse) the proxy and return its URL.
    stop_proxy: Kill the proxy and remove its state files.
"""

from __future__ import annotations

import os
import socket
import subprocess
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Optional

from nasim import config
from nasim.util import have, log


def autodetect() -> Optional[str]:
    """Return a free-claude-code source dir, honouring config/env then guesses.

    Returns:
        Optional[str]: Absolute path to a checkout containing ``api/app.py``, else None.
    """
    cfg = config.get_config()
    candidates = []
    if cfg.fcc_src_dir:
        candidates.append(cfg.fcc_src_dir)
    home = str(config.HOME)
    candidates += [
        f"{home}/prj/salim/nasim/code/free-claude-code",
        f"{home}/prj/nasim/code/free-claude-code",
        os.path.join(os.getcwd(), "..", "free-claude-code"),
        os.path.join(os.getcwd(), "..", "..", "free-claude-code"),
    ]
    found: Optional[str] = None
    for c in candidates:
        if c and Path(c, "api", "app.py").is_file():
            found = str(Path(c).resolve())
            break
    return found


def available() -> bool:
    """Return whether the fcc proxy can be started on this machine.

    Returns:
        bool: True if a source dir exists and uvicorn (or uv) is usable.
    """
    src = autodetect()
    ok = False
    if src and have("python3"):
        try:
            import importlib.util

            has_uvicorn = importlib.util.find_spec("uvicorn") is not None
        except (ImportError, ValueError):
            has_uvicorn = False
        ok = has_uvicorn or have("uv")
    return ok


def _find_free_port() -> int:
    """Pick a free TCP port near the nasim local port.

    Returns:
        int: A free port.
    """
    cfg = config.get_config()
    base = cfg.default_local_port + 1
    chosen = base
    for off in (0, 1, 2, 10, 100):
        port = base + off
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            try:
                sock.bind(("127.0.0.1", port))
                chosen = port
                return chosen
            except OSError:
                continue
    with socket.socket() as sock:
        sock.bind(("", 0))
        chosen = sock.getsockname()[1]
    return chosen


def _write_env(a_ollama_url: str, a_model: str, a_port: int) -> Path:
    """Write the temp fcc env file and return its path.

    Args:
        a_ollama_url (str): Base Ollama URL the proxy should target.
        a_model (str): Model tag; normalised to ``ollama/<tag>``.
        a_port (int): Port the proxy should bind.

    Returns:
        Path: The env file path.
    """
    config.STATE_DIR.mkdir(parents=True, exist_ok=True)
    bare = a_model[len("ollama/") :] if a_model.startswith("ollama/") else a_model
    config.FCC_ENV_FILE.write_text(
        "# Auto-generated by nasim for this session. Do not edit.\n"
        f"OLLAMA_BASE_URL={a_ollama_url}\n"
        f"MODEL=ollama/{bare}\n"
        "ANTHROPIC_AUTH_TOKEN=ollama\n"
        f"PORT={a_port}\n"
        "HOST=127.0.0.1\n"
        "FCC_OPEN_BROWSER=false\n"
        "ENABLE_MODEL_THINKING=true\n",
        encoding="utf-8",
    )
    return config.FCC_ENV_FILE


def start_proxy(a_ollama_url: str, a_model: str) -> tuple[bool, str]:
    """Start (or reuse) the fcc proxy and return ``(success, url)``.

    On failure, ``url`` is the original Ollama URL so the caller can fall back to
    the direct path.

    Args:
        a_ollama_url (str): Base Ollama URL from the active transport.
        a_model (str): Model tag.

    Returns:
        tuple[bool, str]: success flag and the URL to use.
    """
    config.STATE_DIR.mkdir(parents=True, exist_ok=True)

    # Reuse a healthy existing proxy.
    if config.FCC_PID_FILE.exists():
        try:
            oldpid = int(config.FCC_PID_FILE.read_text().strip())
            os.kill(oldpid, 0)
            oldport = config.FCC_PORT_FILE.read_text().strip() if config.FCC_PORT_FILE.exists() else "0"
            return True, f"http://127.0.0.1:{oldport}"
        except (ValueError, ProcessLookupError, OSError):
            stop_proxy()

    if not available():
        log("fcc proxy not available (NASIM_FCC_SRC_DIR or uvicorn missing); using direct ollama")
        return False, a_ollama_url

    src = autodetect() or ""
    port = _find_free_port()
    envf = _write_env(a_ollama_url, a_model, port)
    bare = a_model[len("ollama/") :] if a_model.startswith("ollama/") else a_model
    log(f"starting isolated fcc proxy (ollama via nasim -> fcc on :{port}, model=ollama/{bare}) ...")

    env = dict(os.environ, FCC_ENV_FILE=str(envf), PYTHONPATH=src)
    if have("uv"):
        cmd = [
            "uv", "--directory", src, "--project", ".", "run", "--with", "uvicorn", "--",
            "python", "-m", "uvicorn", "--app-dir", src, "--factory", "api.app:create_app",
            "--host", "127.0.0.1", "--port", str(port), "--log-level", "error",
            "--timeout-graceful-shutdown", "3",
        ]
    else:
        cmd = [
            "python3", "-m", "uvicorn", "--app-dir", src, "--factory", "api.app:create_app",
            "--host", "127.0.0.1", "--port", str(port), "--log-level", "error",
            "--timeout-graceful-shutdown", "3",
        ]
    proc = subprocess.Popen(cmd, env=env, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    config.FCC_PID_FILE.write_text(str(proc.pid), encoding="utf-8")
    config.FCC_PORT_FILE.write_text(str(port), encoding="utf-8")

    proxy_url = f"http://127.0.0.1:{port}"
    healthy = False
    for _ in range(8):
        try:
            with urllib.request.urlopen(proxy_url + "/health", timeout=1) as resp:
                if resp.status == 200:
                    healthy = True
                    break
        except (urllib.error.URLError, OSError):
            pass
        time.sleep(0.6)

    if healthy:
        log(f"fcc proxy healthy at {proxy_url}")
        return True, proxy_url

    log("fcc proxy failed to become healthy; killing and falling back to direct")
    try:
        proc.kill()
    except OSError:
        pass
    for f in (config.FCC_PID_FILE, config.FCC_PORT_FILE, config.FCC_ENV_FILE):
        f.unlink(missing_ok=True)
    return False, a_ollama_url


def stop_proxy() -> None:
    """Kill the fcc proxy if running and remove its state files."""
    killed = False
    if config.FCC_PID_FILE.exists():
        try:
            pid = int(config.FCC_PID_FILE.read_text().strip())
            os.kill(pid, 15)
            time.sleep(0.3)
            try:
                os.kill(pid, 9)
            except ProcessLookupError:
                pass
            killed = True
        except (ValueError, ProcessLookupError, OSError):
            pass
        config.FCC_PID_FILE.unlink(missing_ok=True)
    for f in (config.FCC_PORT_FILE, config.FCC_ENV_FILE):
        f.unlink(missing_ok=True)
    if killed:
        log("fcc proxy stopped")
